### ISSUE TITLE
[feat] Flutter端生成代码框架

### ISSUE THREAD

**Issue by foxsofter** [flutter-thrio/flutter_thrio#4]
虽然是混合栈框架，但引入后建议能用 Flutter 实现的都用 Flutter 实现，兼容原生路由栈只是为了复用既有功能和将来可能依赖的外部原生代码，所以本框架的重心之后会放在 Flutter 端的开发体验。

通过 yaml 文件来配置 Flutter 所有页面的路径，类似如下：

``` yaml
app:
  order:
    home:
    list:
    detail:
    handle:
      home:
      result:
  waybill:
    home:
    list:
    detail:
    handle:
      home:
      result:
```

根据该配置，生成模块化的 Flutter 代码框架。实际使用时，url 末尾的 home 可以省略掉。
